# Exploration of Data Sources
* listings.csv.gz - Detailed listings data for New York City
* listings.csv - Summary information and metrics for listings in New York City
* calendar.csv.gz - Detailed calendar data for listings in New York City
* reviews.csv.gz - Detailed review data for listings in New York City
* reviews.csv - Summary review data and listing ID
* neighbourhoods.csv - Neighbourhood list for geo filter. Sourced from city or open source GIS files
* neighbourhoods.geojson - GeoJSON file of neighbourhoods of the city

For the purposes of this notebook, each file will be explored separately.

In [1]:
import pandas as pd 
import json
import os

# function to summarize data
# param: df dataframe
# print number of variables, data type counts, and variable names
def summarizeData(df):
    print("Number of Variables: {:d}\n".format(df.shape[1]))
    print("Number of Observations: {:d}\n".format(df.shape[0]))
    print("Data types:")
    print(df.dtypes.value_counts())    
    print("\nColumn Names by Type:\n")
    g = df.columns.to_series().groupby(df.dtypes).groups
    for item in g.items():
        print(item)

## Available Data

In [2]:
# Data directory
folder = r'C:\Users\ke392d\Desktop\Master\LTP_Learning Together Program\LTP - Masters Data Science\MAR653\_team_project\data'
# function to get absolute filepaths in a directory
# param directory: absolute directory name
# yields absolute file paths
def absoluteFilePaths(directory):
   for dirpath,_,filenames in os.walk(directory):
       for f in filenames:
           yield os.path.abspath(os.path.join(dirpath, f)) 
# get list of absolute file paths in current directory
myGenerator = absoluteFilePaths(folder)
filelist = []
for f in myGenerator:
    filelist.append(f)
print(filelist)    

['C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\listings.csv', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\neighbourhoods.csv', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\neighbourhoods.geojson', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\reviews.csv', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\calendar_detailed\\calendar.csv.gz', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR653\\_team_project\\data\\listings_detailed\\listings.csv.gz', 'C:\\Users\\ke392d\\Desktop\\Master\\LTP_Learning Together Program\\LTP - Masters Data Science\\MAR6

## File: listings.csv.gz (detailed)
* Detailed Listings data for New York City
* Contains 50599 observations of 43 numeric and 63 object variables

In [3]:
fname = folder + '\\listings_detailed\\listings.csv.gz'
df = pd.read_csv(fname, compression='gzip')
df.describe()

C:\Users\ke392d\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


id     scrape_id  thumbnail_url  medium_url  xl_picture_url  \
count  5.059900e+04  5.059900e+04            0.0         0.0             0.0   
mean   2.137380e+07  2.019120e+13            NaN         NaN             NaN   
std    1.242864e+07  1.221496e+01            NaN         NaN             NaN   
min    2.595000e+03  2.019120e+13            NaN         NaN             NaN   
25%    1.009891e+07  2.019120e+13            NaN         NaN             NaN   
50%    2.154642e+07  2.019120e+13            NaN         NaN             NaN   
75%    3.271780e+07  2.019120e+13            NaN         NaN             NaN   
max    4.058402e+07  2.019120e+13            NaN         NaN             NaN   

            host_id  host_acceptance_rate  host_listings_count  \
count  5.059900e+04                   0.0         50036.000000   
mean   7.893854e+07                   NaN            17.388720   
std    9.095944e+07                   NaN           111.558158   
min    2.438000e+03                   NaN             0.000000   
25%    8.925493e+06                   NaN             1.000000   
50%    3.572660e+07                   NaN             1.000000   
75%    1.293330e+08                   NaN             2.000000   
max    3.143682e+08                   NaN          1767.000000   

       host_total_listings_count      latitude  ...  \
count               50036.000000  50599.000000  ...   
mean                   17.388720     40.728743  ...   
std                   111.558158      0.055004  ...   
min                     0.000000     40.499790  ...   
25%                     1.000000     40.689550  ...   
50%                     1.000000     40.722880  ...   
75%                     2.000000     40.763030  ...   
max                  1767.000000     40.916860  ...   

       review_scores_cleanliness  review_scores_checkin  \
count               39415.000000           39385.000000   
mean                    9.273272               9.739647   
std                     1.079284               0.735555   
min                     2.000000               2.000000   
25%                     9.000000              10.000000   
50%                    10.000000              10.000000   
75%                    10.000000              10.000000   
max                    10.000000              10.000000   

       review_scores_communication  review_scores_location  \
count                 39404.000000            39381.000000   
mean                      9.743579                9.580585   
std                       0.751233                0.758823   
min                       2.000000                2.000000   
25%                      10.000000                9.000000   
50%                      10.000000               10.000000   
75%                      10.000000               10.000000   
max                      10.000000               10.000000   

       review_scores_value  calculated_host_listings_count  \
count         39382.000000                    50599.000000   
mean              9.383272                        7.330916   
std               0.928692                       32.757485   
min               2.000000                        1.000000   
25%               9.000000                        1.000000   
50%              10.000000                        1.000000   
75%              10.000000                        2.000000   
max              10.000000                      310.000000   

       calculated_host_listings_count_entire_homes  \
count                                 50599.000000   
mean                                      5.615170   
std                                      32.293312   
min                                       0.000000   
25%                                       0.000000   
50%                                       1.000000   
75%                                       1.000000   
max                                     310.000000   

       calculated_host_listings_count_private_rooms  \
count        

In [4]:
summarizeData(df)

Number of Variables: 106

Number of Observations: 50599

Data types:
object     63
float64    22
int64      21
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['id', 'scrape_id', 'host_id', 'accommodates', 'guests_included',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms'],
      dtype='object'))
(dtype('float64'), Index(['thumbnail_url', 'medium_url', 'xl_picture_url', 'host_acceptance_rate',
       'host_listings_count', 'host_total_listings_count', 'latitude',
       'longitude', 'bathrooms', 'bedrooms', 'beds', 'square_feet',
      

### Sample Observation

In [5]:
df.head()

id                        listing_url       scrape_id last_scraped  \
0  2595  https://www.airbnb.com/rooms/2595  20191204162729   2019-12-07   
1  3831  https://www.airbnb.com/rooms/3831  20191204162729   2019-12-07   
2  5099  https://www.airbnb.com/rooms/5099  20191204162729   2019-12-06   
3  5121  https://www.airbnb.com/rooms/5121  20191204162729   2019-12-06   
4  5178  https://www.airbnb.com/rooms/5178  20191204162729   2019-12-05   

                                        name  \
0                      Skylit Midtown Castle   
1            Cozy Entire Floor of Brownstone   
2  Large Cozy 1 BR Apartment In Midtown East   
3                            BlissArtsSpace!   
4           Large Furnished Room Near B'way    

                                             summary  \
0  Beautiful, spacious skylit studio in the heart...   
1  Urban retreat: enjoy 500 s.f. floor in 1899 br...   
2  My large 1 bedroom apartment has a true New Yo...   
3                                                NaN   
4  Please don’t expect the luxury here just a bas...   

                                               space  \
0  - Spacious (500+ft²), immaculate and nicely fu...   
1  Greetings!      We own a double-duplex brownst...   
2  I have a large 1 bedroom apartment centrally l...   
3  HELLO EVERYONE AND THANKS FOR VISITING BLISS A...   
4  You will use one large, furnished, private roo...   

                                         description experiences_offered  \
0  Beautiful, spacious skylit studio in the heart...                none   
1  Urban retreat: enjoy 500 s.f. floor in 1899 br...                none   
2  My large 1 bedroom apartment has a true New Yo...                none   
3  HELLO EVERYONE AND THANKS FOR VISITING BLISS A...                none   
4  Please don’t expect the luxury here just a bas...                none   

                               neighborhood_overview  ... instant_bookable  \
0  Centrally located in the heart of Manhattan ju...  ...                f   
1  Just the right mix of urban center and local n...  ...                f   
2  My neighborhood in Midtown East is called Murr...  ...                f   
3                                                NaN  ...                f   
4    Theater district, many restaurants around here.  ...                f   

  is_business_travel_ready          cancellation_policy  \
0                        f  strict_14_with_grace_period   
1                        f                     moderate   
2                        f                     moderate   
3                        f  strict_14_with_grace_period   
4                        f  strict_14_with_grace_period   

  require_guest_profile_picture require_guest_phone_verification  \
0                             t                                t   
1                             f                                f   
2                             t                                t   
3                             f                                f   
4                             f                                f   

   calculated_host_listings_count  \
0                               1   
1                               1   
2                               1   
3                               1   
4                               1   

   calculated_host_listings_count_entire_homes  \
0                                            1   
1                                            1   
2                                            1   
3                                            0   
4                                            0   

  calculated_host_listings_count_private_rooms  \
0                                            0   
1                                            0   
2                                            0   
3                                            1   
4                                            1   

   calculated_host_listings_count_shared_rooms  reviews_per_month  
0       

## File: listings.csv (summary)
* Summary information and metrics for listings in New York City (good for visualizations)
* Contains 50599 observations of 10 numeric and 6 object variables

In [6]:
fname = folder + '\\listings.csv'
df = pd.read_csv(fname)
df.describe()

id       host_id      latitude     longitude         price  \
count  5.059900e+04  5.059900e+04  50599.000000  50599.000000  50599.000000   
mean   2.137380e+07  7.893854e+07     40.728743    -73.950762    158.171782   
std    1.242864e+07  9.095944e+07      0.055004      0.047606    348.089562   
min    2.595000e+03  2.438000e+03     40.499790    -74.247870      0.000000   
25%    1.009891e+07  8.925493e+06     40.689550    -73.982930     69.000000   
50%    2.154642e+07  3.572660e+07     40.722880    -73.955050    105.000000   
75%    3.271780e+07  1.293330e+08     40.763030    -73.934200    175.000000   
max    4.058402e+07  3.143682e+08     40.916860    -73.712990  10000.000000   

       minimum_nights  number_of_reviews  reviews_per_month  \
count    50599.000000       50599.000000       40379.000000   
mean         7.531908          24.809225           1.405862   
std         22.454271          47.317882           1.695551   
min          1.000000           0.000000           0.010000   
25%          1.000000           1.000000           0.190000   
50%          3.000000           6.000000           0.740000   
75%          5.000000          25.000000           2.110000   
max       1250.000000         675.000000          52.630000   

       calculated_host_listings_count  availability_365  
count                    50599.000000      50599.000000  
mean                         7.330916        112.785944  
std                         32.757485        135.891028  
min                          1.000000          0.000000  
25%                          1.000000          0.000000  
50%                          1.000000         42.000000  
75%                          2.000000        225.000000  
max                        310.000000        365.000000

In [7]:
summarizeData(df)

Number of Variables: 16

Number of Observations: 50599

Data types:
int64      7
object     6
float64    3
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['id', 'host_id', 'price', 'minimum_nights', 'number_of_reviews',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object'))
(dtype('float64'), Index(['latitude', 'longitude', 'reviews_per_month'], dtype='object'))
(dtype('O'), Index(['name', 'host_name', 'neighbourhood_group', 'neighbourhood',
       'room_type', 'last_review'],
      dtype='object'))


### Sample Observation

In [8]:
df.head()

id                                       name  host_id    host_name  \
0  2595                      Skylit Midtown Castle     2845     Jennifer   
1  3831            Cozy Entire Floor of Brownstone     4869  LisaRoxanne   
2  5099  Large Cozy 1 BR Apartment In Midtown East     7322        Chris   
3  5121                            BlissArtsSpace!     7356        Garon   
4  5178           Large Furnished Room Near B'way      8967     Shunichi   

  neighbourhood_group       neighbourhood  latitude  longitude  \
0           Manhattan             Midtown  40.75362  -73.98377   
1            Brooklyn        Clinton Hill  40.68514  -73.95976   
2           Manhattan         Murray Hill  40.74767  -73.97500   
3            Brooklyn  Bedford-Stuyvesant  40.68688  -73.95596   
4           Manhattan      Hell's Kitchen  40.76489  -73.98493   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0  Entire home/apt    225              10                 48  2019-11-04   
1  Entire home/apt     89               1                295  2019-11-22   
2  Entire home/apt    200               3                 78  2019-10-13   
3     Private room     60              29                 49  2017-10-05   
4     Private room     79               2                454  2019-11-21   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.39                               1                 1  
1               4.67                               1                 1  
2               0.60                               1                19  
3               0.38                               1               365  
4               3.52                               1               242

## File: reviews.csv.gz (detailed)
* Detailed Review Data for listings in New York City
* Contains 1255322 observations of 3 numeric and 3 object variables

In [9]:
fname = folder + '\\reviews_detailed\\reviews.csv.gz'
df = pd.read_csv(fname, compression='gzip')
df.describe()

listing_id            id   reviewer_id
count  1.255322e+06  1.255322e+06  1.255322e+06
mean   1.396211e+07  2.918422e+08  8.324934e+07
std    1.076478e+07  1.734486e+08  7.820263e+07
min    2.595000e+03  9.030000e+02  1.000000e+00
25%    4.081800e+06  1.415657e+08  1.876831e+07
50%    1.315684e+07  2.900042e+08  5.592106e+07
75%    2.173354e+07  4.526637e+08  1.324934e+08
max    4.056566e+07  5.736112e+08  3.146917e+08

In [10]:
summarizeData(df)

Number of Variables: 6

Number of Observations: 1255322

Data types:
object    3
int64     3
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id', 'id', 'reviewer_id'], dtype='object'))
(dtype('O'), Index(['date', 'reviewer_name', 'comments'], dtype='object'))


### Sample Observation

In [11]:
df.head()

listing_id     id        date  reviewer_id reviewer_name  \
0        2595  17857  2009-11-21        50679          Jean   
1        2595  19176  2009-12-05        53267          Cate   
2        2595  19760  2009-12-10        38960         Anita   
3        2595  34320  2010-04-09        71130       Kai-Uwe   
4        2595  46312  2010-05-25       117113        Alicia   

                                            comments  
0  Notre séjour de trois nuits.\r\nNous avons app...  
1                                  Great experience.  
2  I've stayed with my friend at the Midtown Cast...  
3  We've been staying here for about 9 nights, en...  
4  We had a wonderful stay at Jennifer's charming...

## File: reviews.csv (summary)
* Summary Review data and Listing ID (to facilitate time based analytics and visualizations linked to a listing)
* Contains 1255322 observations of 1 numeric and 1 object variables
* These are observations of review dates by listing ID.

In [12]:
fname = folder + '\\reviews.csv'
df = pd.read_csv(fname)
df.describe()

listing_id
count  1.255322e+06
mean   1.396211e+07
std    1.076478e+07
min    2.595000e+03
25%    4.081800e+06
50%    1.315684e+07
75%    2.173354e+07
max    4.056566e+07

In [13]:
summarizeData(df)

Number of Variables: 2

Number of Observations: 1255322

Data types:
object    1
int64     1
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id'], dtype='object'))
(dtype('O'), Index(['date'], dtype='object'))


### Sample Observation

In [14]:
df.head()

listing_id        date
0        2595  2009-11-21
1        2595  2009-12-05
2        2595  2009-12-10
3        2595  2010-04-09
4        2595  2010-05-25

## File: calendar.csv.gz (detailed)
> Detailed Calendar Data for listings in New York City

In [15]:
fname = folder + '\\calendar_detailed\\calendar.csv.gz'
df = pd.read_csv(fname, compression='gzip')
df.describe()

listing_id  minimum_nights  maximum_nights
count  1.847016e+07    1.846950e+07    1.846950e+07
mean   2.137365e+07    8.528041e+00    6.886948e+05
std    1.242861e+07    3.029394e+01    3.841186e+07
min    2.595000e+03    1.000000e+00    1.000000e+00
25%    1.009889e+07    1.000000e+00    2.900000e+01
50%    2.154642e+07    3.000000e+00    1.125000e+03
75%    3.271789e+07    5.000000e+00    1.125000e+03
max    4.058402e+07    3.456000e+03    2.147484e+09

In [16]:
summarizeData(df)

Number of Variables: 7

Number of Observations: 18470156

Data types:
object     4
float64    2
int64      1
dtype: int64

Column Names by Type:

(dtype('int64'), Index(['listing_id'], dtype='object'))
(dtype('float64'), Index(['minimum_nights', 'maximum_nights'], dtype='object'))
(dtype('O'), Index(['date', 'available', 'price', 'adjusted_price'], dtype='object'))


### Sample Observation

In [17]:
df.head()

listing_id        date available    price adjusted_price  minimum_nights  \
0       19812  2019-12-05         f  $105.00        $105.00             3.0   
1        2595  2019-12-06         f  $175.00        $175.00            10.0   
2        2595  2019-12-07         f  $175.00        $175.00            10.0   
3        2595  2019-12-08         f  $175.00        $175.00            10.0   
4        2595  2019-12-09         f  $175.00        $175.00            10.0   

   maximum_nights  
0            90.0  
1          1125.0  
2          1125.0  
3          1125.0  
4          1125.0

## File: neighbourhoods.csv
> Neighbourhood list for geo filter. Sourced from city or open source GIS files.

In [18]:
fname = folder + '\\neighbourhoods.csv'
df = pd.read_csv(fname)
df.describe()

neighbourhood_group neighbourhood
count                  230           230
unique                   5           230
top                 Queens     Laurelton
freq                    53             1

In [19]:
summarizeData(df)

Number of Variables: 2

Number of Observations: 230

Data types:
object    2
dtype: int64

Column Names by Type:

(dtype('O'), Index(['neighbourhood_group', 'neighbourhood'], dtype='object'))


### Sample Observation

In [20]:
df.head()

neighbourhood_group neighbourhood
0               Bronx      Allerton
1               Bronx    Baychester
2               Bronx       Belmont
3               Bronx     Bronxdale
4               Bronx   Castle Hill

## File: neighbourhoods.geojson
> GeoJSON file of neighbourhoods of the city

In [21]:
fname = folder + '\\neighbourhoods.geojson'
with open(fname,'r') as fin:
    data = json.loads(fin.read())

In [22]:
data.keys()

dict_keys(['type', 'features'])

In [23]:
data['type']

'FeatureCollection'

In [24]:
print("There are {:d} feature sets in the collection".format(len(data['features'])))

There are 233 feature sets in the collection


### Sample Observation

In [25]:
# inspect first feature set
data['features'][0]

{'type': 'Feature',
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[-73.766708, 40.614911],
     [-73.768253, 40.614878],
     [-73.773977, 40.616004],
     [-73.773631, 40.616327],
     [-73.768735, 40.620901],
     [-73.767459, 40.620511],
     [-73.766978, 40.616919],
     [-73.766708, 40.614911]]]]},
 'properties': {'neighbourhood': 'Bayswater', 'neighbourhood_group': 'Queens'}}

Each feature set contains latitude and longitude coordinates specific to neighbourhood and neighbourhood group.

In [26]:
# all neighbourhood groups
neighbourhoodgroups = set([f['properties']['neighbourhood_group'] for f in data['features']])
print(neighbourhoodgroups)

{'Bronx', 'Queens', 'Staten Island', 'Manhattan', 'Brooklyn'}


In [27]:
# all neighbourhoods by neighbourhood group
for group in neighbourhoodgroups:
    # neighbourhoods respective to neighbourhood group
    nnames = [f['properties']['neighbourhood'] for f in data['features'] if f['properties']['neighbourhood_group'] == group]
    print('\n',"group:",group)
    print(" neighbourhoods:{:d}".format(len(nnames)),'\n')
    print(nnames)


 group: Bronx
 neighbourhoods:50 

['Allerton', 'City Island', 'Fordham', 'Belmont', 'Soundview', 'Baychester', 'Mott Haven', 'Bronxdale', 'City Island', 'Castle Hill', 'Claremont Village', 'Clason Point', 'Co-op City', 'Concourse', 'Concourse Village', 'Mount Eden', 'Country Club', 'Mount Hope', 'East Morrisania', 'Fieldston', 'Eastchester', 'Edenwald', 'Parkchester', 'Pelham Bay', 'Highbridge', 'Pelham Gardens', 'Hunts Point', 'Morris Park', 'Kingsbridge', 'Morrisania', 'Longwood', 'Norwood', 'Morris Heights', 'Melrose', 'Olinville', 'North Riverdale', 'Port Morris', 'Riverdale', 'Schuylerville', 'Spuyten Duyvil', 'Van Nest', 'Throgs Neck', 'Tremont', 'Unionport', 'University Heights', 'Wakefield', 'West Farms', 'Woodlawn', 'Westchester Square', 'Williamsbridge']

 group: Queens
 neighbourhoods:55 

['Bayswater', 'Ditmars Steinway', 'Ozone Park', 'Whitestone', 'Arverne', 'Astoria', 'Bayside', 'Bay Terrace', 'Bayswater', 'Belle Harbor', 'Bellerose', 'Breezy Point', 'Briarwood', 'Camb